# Generated by Django 5.2.17 on 2026-08-16 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='Nomor Seri')),
                ('name', models.CharField(max_length=150, verbose_name='Nama Barang')),
                ('brand', models.CharField(max_length=100, verbose_name='Merk')),
                ('model_type', models.CharField(blank=True, max_length=100, verbose_name='Tipe')),
                ('acquisition_year', models.PositiveIntegerField(verbose_name='Tahun Perolehan')),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('scheduled', 'Dijadwalkan'), ('under_repair', 'Dalam Perbaikan'), ('damaged', 'Rusak')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True, verbose_name='Keterangan')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='equipment_photos/', verbose_name='Foto Barang')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('location_name', models.CharField(blank=True, max_length=150, verbose_name='Lokasi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Equipment',
                'verbose_name_plural': 'Equipment',
                'ordering': ['name'],
            },
        ),
    ]
