# Generated by Django 5.2.17 on 2026-08-18 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_alter_equipment_brand_alter_equipment_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='acquisition_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Tahun Perolehan'),
        ),
    ]
