# Generated by Django 5.2.17 on 2026-08-16 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField(verbose_name='Tanggal Jadwal')),
                ('maintenance_type', models.CharField(choices=[('routine', 'Perawatan Rutin'), ('repair', 'Perbaikan')], default='routine', max_length=20, verbose_name='Jenis Perawatan')),
                ('notes', models.TextField(blank=True, verbose_name='Catatan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_schedules', to='equipment.equipment')),
            ],
            options={
                'verbose_name': 'Maintenance Schedule',
                'verbose_name_plural': 'Maintenance Schedules',
                'ordering': ['scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Tanggal Schedule')),
                ('technician', models.CharField(blank=True, max_length=100, verbose_name='Teknisi')),
                ('action_taken', models.TextField(blank=True, verbose_name='Tindakan')),
                ('result', models.CharField(choices=[('pending', 'Sedang Dijadwalkan'), ('in_progress', 'Sedang Dikerjakan'), ('completed', 'Selesai Pengerjaan'), ('failed', 'Gagal')], default='pending', max_length=20)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Biaya')),
                ('photo_before', models.ImageField(blank=True, null=True, upload_to='maintenance_photos/before/', verbose_name='Foto Sebelum')),
                ('photo_after', models.ImageField(blank=True, null=True, upload_to='maintenance_photos/after/', verbose_name='Foto Sesudah')),
                ('photo_receipt', models.ImageField(blank=True, null=True, upload_to='maintenance_photos/receipts/', verbose_name='Foto Kwitansi')),
                ('completed_date', models.DateField(blank=True, null=True, verbose_name='Tanggal Selesai')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('schedule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='log', to='maintenance.maintenanceschedule')),
            ],
            options={
                'verbose_name': 'Maintenance Log',
                'verbose_name_plural': 'Maintenance Logs',
                'ordering': ['-updated_at'],
            },
        ),
    ]
